# Sample configuration for awesome-cheap-flights (lightweight for tests)
currency: USD
# currency: KRW # Korean Won
# currency: JPY # Japanese Yen
# currency: CNY # Chinese Yuan

departures:
  - ICN  # Seoul Incheon

destinations:
  - FUK  # Fukuoka

itineraries:
  - outbound:
      start: 2026-01-01
      end: 2026-01-01
    inbound: 2026-01-04

output_path: output/sample.csv
request_delay: 0.5
max_retries: 1
max_leg_results: 3

