schema_version: v2

# 기본 검색 옵션을 묶어서 정의한다.
defaults:
  currency: USD            # 전체 여정의 기본 통화.
  passengers: 1            # 성인 승객 수.
  request:
    delay: 0.5             # 요청 간 대기 시간(초 단위).
    retries: 1             # 실패 시 재시도 횟수.
    max_leg_results: 3     # 구간당 최대 수집 편수.
  filters:
    max_stops: 1           # 기본 허용 경유 횟수.
    include_hidden: true   # 숨겨진 경유 탐색 전역 활성화.
    max_hidden_hops: 1     # 숨겨진 경유 탐색 시 허용 경유 수.
  output:
    directory: output
    filename_pattern: "{plan}_{timestamp}.csv"

# 하나의 여행 계획을 정의한다.
plans:
  - name: sample-hop
    places:
      home:
        - ICN # Seoul Incheon
      city:
        - FUK # Fukuoka
        - HKG # Hong Kong
    path: [home, city, home]
    departures:
      "home->city":
        dates: ["2026-01-01", "2026-01-02"]   # 첫 이동 날짜들.
      "city->home":
        window:
          start: "2026-01-04"                   # 귀국 시작일.
          end: "2026-01-05"                     # 귀국 종료일.
    filters:
      "home->city":
        max_stops: 0                            # 첫 구간은 직항만 허용.
    options:
      include_hidden: true                      # 숨겨진 도시 조합 추가 탐색.
      max_hidden_hops: 1

# 네트워크 조건을 비워두면 시스템 기본값 사용.
http_proxy: null
concurrency: 1
