schema_version: v2

# Define global defaults for every plan.
defaults:
  currency: USD            # Base currency for entire journey.
  passengers: 1            # Number of adult travelers.
  request:
    delay: 0.5             # Delay between requests in seconds.
    retries: 1             # Retry count for failed fetches.
    max_leg_results: 3     # Maximum flights stored per leg.
    seat: economy          # Cabin class (economy, premium-economy, business, first).
  filters:
    max_stops: 1           # Global stop allowance per leg.
    include_hidden: true   # Enable hidden-leg discovery everywhere.
    max_hidden_hops: 1     # Hidden searches allow one connection.
  output:
    directory: output
    filename_pattern: "{plan}_{timestamp}.csv"
  itinerary:
    leg_limit: 0           # 0 means unlimited (set 10 for a conservative cap).
    max_combinations: 0    # 0 means unlimited itinerary combinations.

# Define a single travel plan.
plans:
  - name: sample-hop
    places:
      home:
        - ICN # Seoul Incheon
      city:
        - FUK # Fukuoka
        - HKG # Hong Kong
    path: [home, city, home]
    departures:
      "home->city":
        dates: ["2026-01-01", "2026-01-02"]   # Outbound departure choices.
        max_stops: 0                            # Limit outbound to nonstop only.
      "city->home":
        window:
          start: "2026-01-04"                   # Return window start date.
          end: "2026-01-05"                     # Return window end date.
    filters:
      "home->city":
        max_stops: 0                            # Keep outbound nonstop as well.
    options:
      include_hidden: true                      # Add hidden city combinations.
      max_hidden_hops: 1

# Leave network settings empty to use system defaults.
google_cookie_file: null
# google_cookie: "SID=...; HSID=..."
http_proxy: null
concurrency: 1
